print("hello, world!")
print('I can\'t believe it!')
print('He didn\'t say \"I hate python\"!')
print('MWF')
print('\tEECS 168')
print('\tEECS 140')
print('\tMATH 126')
print('Below is the word\n\tapples')
print('Here is a slash \\')
