print('text')
print("text")
print("I'm excited for the weekend")
print('They said, "Hi."')
print("They said, \"I can't\"")
print('They said, "I can\'t"')
print('MWF\n\tEECS 168')
print('The secret number is', 55)
print(10+5)
print('10+5 =', 10+5)
